services:
  reporting_service:
    build:
      context: ../..
      dockerfile: packages/reporting-service/Dockerfile
    container_name: reporting_service
    env_file:
      - ../../.env
      - .env
    environment:
      - NODE_ENV=development
      - SERVICE_INTERNAL_PORT=3009
      - SERVICE_HOST_PORT=3009
    ports:
      - "3009:3009"
    volumes:
      - ../..:/app:cached
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3009/api/health  || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped
