apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  namespace: prod
  labels:
    app: storage-service
spec:
  replicas: 2 # banyaknya replika
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      serviceAccountName: default-sa
      containers:
        - name: storage
          image: rahvanna/storage-service:latest
          ports:
            - containerPort: 4001
              name: http
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: PORT
              value: '4001'
            - name: SERVICE_NAME
              value: 'storage-service'
          resources:
            requests: # minimum CPU (100m) dan memori (64Mi)
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 125m
              memory: 192Mi
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 4001
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 4001
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: prod
  labels:
    app: storage-service
spec:
  selector:
    app: storage-service
  ports:
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: http
  type: ClusterIP
