apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: prod
data:
  APP_NAME: 'mbg-backend-microservice'

  # RabbitMQ
  RABBITMQ_HOST_PORT: '5672'
  RABBITMQ_MANAGEMENT_HOST_PORT: '15672'

  # Redis
  REDIS_HOST_PORT: '6380'
  REDIS_MANAGEMENT_HOST_PORT: '5544'

  # Supabase
  DB_HOST: '128.199.77.145'
  DB_PORT: '5481'
  DB_NAME: 'mbgreport'

  # List Port
  PORT_AUTH: '3000'
  PORT_USER: '3001'
  PORT_TRACKING: '3002'

  # List Service
  USER_SERVICE: 'http://user-service:3001/api'

  # smtp
  EMAIL_HOST: 'smtp.office365.com'
  EMAIL_PORT: '587'
  EMAIL_SECURE: 'false'
  NODE_ENV: 'DEVELOPMENT'
  # minio
  # MINIO_ENDPOINT_SERVER: 'minio'
  # MINIO_PORT: '9000'
  # MINIO_CONSOLE_PORT: '9001'
  MINIO_ENDPOINT_SERVER: '128.199.77.145'
  MINIO_ENDPOINT: 'https://dev-mbg-be.midigi.id/storage/api/storage'
  MINIO_PORT: '9000'
  MINIO_CONSOLE_PORT: '9001'

  # frontend
  FRONTEND_URL: 'https://dev-mbg.midigi.id'
