apiVersion: v1
kind: Secret
metadata:
  name: common-secret
  namespace: prod
type: Opaque
stringData:
  # RabbitMQ
  RABBITMQ_USER: 'user'
  RABBITMQ_PASS: 'password'
  RABBITMQ_URL: 'amqp://user:password@rabbitmq:5672'

  # Redis
  REDIS_USER: 'user'
  REDIS_PASS: 'password'

  # DB
  DB_USER: 'postgres.yiokveqrkxvdhzkqcyrd'
  DB_PASSWORD: 'vHb1mSnZgEV8NV5u'
  DATABASE_URL: 'postgresql://postgres.yiokveqrkxvdhzkqcyrd:vHb1mSnZgEV8NV5u@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres'

  # smtp
  EMAIL_USER: 'alexis.nova.hartley@ptn-techlabs.com'
  EMAIL_PASS: '5SyW4H$&N5t#m.fu'

  # minio
  MINIO_ROOT_USER: 'minioadmin'
  MINIO_ROOT_PASSWORD: 'minioadmin123'
  MINIO_PORT: '9000'
  MINIO_CONSOLE_PORT: '9001'
