apiVersion: v1
kind: Secret
metadata:
  name: common-secret
  namespace: prod
type: Opaque
stringData:
  # RabbitMQ
  RABBITMQ_USER: ''
  RABBITMQ_PASS: ''
  RABBITMQ_URL: 'amqp://example_user:example_password@rabbitmq:5672'

  # Redis
  REDIS_USER: ''
  REDIS_PASS: ''

  # DB
  DB_USER: ''
  DB_PASSWORD: ''
  DATABASE_URL: ''

  # smtp
  EMAIL_USER: ''
  EMAIL_PASS: ''

  RECAPTCHA_SECRET: ''

  # minio
  MINIO_ROOT_USER: ''
  MINIO_ROOT_PASSWORD: ''
